---
title: "Almond Profit Sensitivity Practice"
author: "Wylie Hampson, Dani Sclafani, Felicia Cruz"
date: "4/18/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(purrr)
```

```{r}
clim_data <- read.delim(here("data", "clim.txt"), sep = " ")
```

```{r}
yield1 <- almond_yield_practice(clim_data)
```

```{r}
nsamples <- 20

deviation1 <- 0.15
base_coef_1 <- 0.015
coef_1 <- runif(min = base_coef_1 - deviation1 * base_coef_1,
                  max = base_coef_1 + deviation1 * base_coef_1,
                  n = nsamples)

deviation3 <- 0.1
base_coef_3 <- 0.07
coef_3 <- runif(min = base_coef_3 - deviation3 * base_coef_3,
                  max = base_coef_3 + deviation3 * base_coef_3,
                  n = nsamples)

parms <- cbind.data.frame(coef_1, coef_3)

yield1 <- coef_1 %>% map(~almond_yield_practice(data = clim_data,
                                                coef_1 = .x))
```

```{r}
tmp <-  map_df(yield1,`[`, c("year")) 
yield1_df <-  data.frame(year = tmp$year, 
                     elect= tmp$year$yield)

```

